### ISSUE TITLE
library does not work with `scipy==0.13.0`

### ISSUE THREAD

**Issue by h-mayorquin** [int-brain-lab/ibllib#753]
The following line that you have:

https://github.com/int-brain-lab/ibllib/blob/634e9dba443d461333d5ce37faf2c7409a8bee53/brainbox/singlecell.py#L6

Does not work with the latest version of scipy (`scipy-1.13.0`). See the following:

```python
import scipy
from scipy.signal import convolve, gaussian
print(scipy.__version__)
1.13.0

{
	"name": "ImportError",
	"message": "cannot import name 'gaussian' from 'scipy.signal' (/home/heberto/miniconda3/envs/neuroconv_env/lib/python3.10/site-packages/scipy/signal/__init__.py)",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 5
      1 import scipy
      3 print(scipy.__version__)
----> 5 from scipy.signal import convolve, gaussian

ImportError: cannot import name 'gaussian' from 'scipy.signal' (/home/heberto/miniconda3/envs/neuroconv_env/lib/python3.10/site-packages/scipy/signal/__init__.py)"
}
```

I tested this with `scipy==0.12` and it works.

You don't have an upper bound on the major (minor?) version for scipy:

https://github.com/int-brain-lab/ibllib/blob/634e9dba443d461333d5ce37faf2c7409a8bee53/requirements.txt#L18

So this means that pip might decide to install a version of your package that can't be imported.

Unfortunatley the release notes of the latest scipy does not seem to be ready so I can confirm if this is intended but something to watch for:

https://docs.scipy.org/doc/scipy/release/1.13.0-notes.html

**Comment by h-mayorquin** [comment]
Thanks @oliche
